apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-estudando
  name: pod-estudando
spec:
  containers:
    - image: nginx
      name: meu-nginx-1
      resources:
        limits:
          cpu: "500m"
          memory: "250Mi"
        requests:
          cpu: "100m"
          memory: "40Mi"
    - image: ubuntu
      name: ubuntu
      command: ["sleep", "3600"]  # Adicionando um comando simples para manter o container em execução
      resources:
        limits:
          cpu: "400m"
          memory: "250Mi"
        requests:
          cpu: "100m"
          memory: "40Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: pod-estudando
      emptyDir:
        sizeLimit: 456Mi